### ISSUE TITLE
jsonDecode Error when initializing SpellChecker Class

### ISSUE THREAD

**Issue by bombyy** [barrust/pyspellchecker#114] opened 2022-01-11 14:15 UTC
Hey,
I found an issue with this module that resulted in a jsonDecodeError when initializing the spellchecker class.

The Error Message:
```
Traceback (most recent call last):
  File "/home/chris/prg/pdfparser/pdfparser.py", line 40, in <module>
    spell_check(text)
  File "/home/chris/prg/pdfparser/pdfparser.py", line 29, in spell_check
    deutsch = SpellChecker(language='de')
  File "/home/chris/prg/pdfparser/.venv/lib/python3.8/site-packages/spellchecker/spellchecker.py", line 68, in __init__
    lang_dict = json.loads(gzip.decompress(json_open).decode("utf-8"))
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
It seems like the `json.loads` function in line 67 of `spellchecker.py` doesn't receive data from the dictionary being read.
The `pkgutil.get_data("spellchecker", filename)` in line 59 seems to return `None` when run.
I replaced it temporarily with `open(<absolute path>{filename}, "rb").read()` and now it seems to work, but I can't figure out why `pkgutil.get_data()` is returning `None`.

**Comment by barrust** [comment] 2022-01-11 15:33
That is odd. I am unable to reproduce this issue. 

Can you confirm which version of pyspellchecker you are using? 

Also, is this being run as an executable? There have been reports of issues similar to this when a script is converted into an executable. There are workarounds, if that is the case, but nothing that can be done from the library directly (that I have found)

- [Issue #105](https://github.com/barrust/pyspellchecker/issues/105)
- [Issue #64](https://github.com/barrust/pyspellchecker/issues/64)

It is odd that your code in the message above shows something I can't find in previous versions, specifically `spellpipchecker`:
`pkgutil.get_data("spellpipchecker", filename)`

**Comment by bombyy** [comment] 2022-01-11 15:50
> That is odd. I am unable to reproduce this issue.
> 
> Can you confirm which version of pyspellchecker you are using?
> 
> Also, is this being run as an executable? There have been reports of issues similar to this when a script is converted into an executable. There are workarounds, if that is the case, but nothing that can be done from the library directly (that I have found)
> 
> * [Issue #105](https://github.com/barrust/pyspellchecker/issues/105)
> * [Issue #64](https://github.com/barrust/pyspellchecker/issues/64)
> 
> It is odd that your code in the message above shows something I can't find in previous versions, specifically `spellpipchecker`: `pkgutil.get_data("spellpipchecker", filename)`

Oh oops the "spellpipchecker" is not actually in there I failed to copy correctly.
I corrected that part in the original issue.
I'm using pyspellchecker version 0.6.2 with Python 3.8.10 on Ubuntu 20.04.

**Comment by barrust** [comment] 2022-01-11 15:57
OK, I tried a pip install to a new conda environment and still didn't get the issue. I too am on a linux box. Are you using a pyinstaller or similar system to make it into an executable?

**Comment by bombyy** [comment] 2022-01-11 16:06
No, I'm running it "normally".
Seems odd to me too, pkgutil.get_data seems to be working normaly except for this instance :/

**Comment by bombyy** [comment] 2022-01-11 16:11
Installing from source seems to resolve the issue :thinking:

**Comment by barrust** [comment] 2022-01-11 16:18
That is really odd. My pip install into conda worked. OK, I think I have enough changes to push a new version out so I will try to do that today. Perhaps we can test again using pip when that drops.

**Comment by barrust** [comment] 2022-01-19 22:48
Does pip installing [v0.6.3](https://github.com/barrust/pyspellchecker/releases/tag/v0.6.3) resolve the issue?

**Comment by bombyy** [comment] 2022-01-20 10:39
Sorry, I will try it out when I'm back home.

**Comment by barrust** [comment] 2022-03-19 12:33
@bombyy, I am going to close this issue. If it isn't resolve, please reopen.

**Closed by barrust** 2022-03-19 12:33 UTC
